# Generated by Django 3.0.3 on 2020-02-25 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('rooms', '0002_auto_20200225_2258'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('timestampedmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.TimeStampedModel')),
                ('name', models.CharField(max_length=80)),
            ],
            options={
                'abstract': False,
            },
            bases=('core.timestampedmodel',),
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('timestampedmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.TimeStampedModel')),
                ('name', models.CharField(max_length=80)),
            ],
            options={
                'abstract': False,
            },
            bases=('core.timestampedmodel',),
        ),
        migrations.CreateModel(
            name='HouseRule',
            fields=[
                ('timestampedmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.TimeStampedModel')),
                ('name', models.CharField(max_length=80)),
            ],
            options={
                'abstract': False,
            },
            bases=('core.timestampedmodel',),
        ),
        migrations.RenameField(
            model_name='room',
            old_name='bedroom',
            new_name='bedrooms',
        ),
        migrations.RemoveField(
            model_name='room',
            name='room_type',
        ),
        migrations.AddField(
            model_name='room',
            name='room_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rooms.RoomType'),
        ),
        migrations.AddField(
            model_name='room',
            name='amenities',
            field=models.ManyToManyField(to='rooms.Amenity'),
        ),
        migrations.AddField(
            model_name='room',
            name='facilities',
            field=models.ManyToManyField(to='rooms.Facility'),
        ),
        migrations.AddField(
            model_name='room',
            name='house_rules',
            field=models.ManyToManyField(to='rooms.HouseRule'),
        ),
    ]
