# Generated by Django 3.0.3 on 2020-03-04 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0002_auto_20200303_2352'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversation',
            old_name='parcitipants',
            new_name='participants',
        ),
    ]
